# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

interval: "500ms"

tasks:
  build:
    desc: build in debug mode
    watch: true
    sources:
      - "hmap*.c"
    cmds:
      - clang -g -O0 -o bin/hmap_test hmap_main.c
    silent: true
